### ISSUE TITLE
Error incorrectly raised: Unable to inflate embedded class FHIR::Coding

### ISSUE THREAD

**Issue by eikes** [fhir-crucible/fhir_models#26]
I am getting a error when using ```FHIR::Json.from_json``` for this file:

https://www.hl7.org/fhir/encounter-example-f002-lung.json

The problem appears to be this line:

     "class": "outpatient",

The version of this file that is in this repository has the following instead:

      "class": {
          "system": "http://hl7.org/fhir/v3/ActCode",
          "code": "AMB",
          "display": "ambulatory"
        },

Having read the specification a bit, it appears, that the first one is correct:

http://www.hl7.org/FHIR/encounter-definitions.html#Encounter.class

I am not quite sure how this whole project works, there is very little documentation, but it appears, that these classes are generated from a definition somehow. But where is this definition? 

Do I correctly understand, that this project uses FHIR STU3, while the hl7.org website refers to DSTU2? If so, how do I generate the classes for DSTU2?

**Comment by jawalonoski** [comment]
The first example is correct if you are using DSTU2, but not STU3.

The classes are generated from the definitions located in `lib/fhir_models/definitions`. The generation will probably not work for DSTU2, because the underlying `StructureDefinitions` changed between DSTU2 and STU3. In the future, we plan to make this `fhir_models` project DSTU2 and STU3 compatible... maybe in the next month.

In the meantime, if you want DSTU2, please use https://github.com/fhir-crucible/fhir_dstu2_models

**Comment by eikes** [comment]
Thank you for pointing me to the fhir_dstu2_models, it appears though, that they depend on MongoDB, which is a no-go for me.

**Comment by arscan** [comment]
We recognized the issue with the Mongoid dependency, which is why we removed it in this version.  Unfortunately we don't have the bandwidth to remove that dependency from the DSTU2 models, but as Jay said, our plan is to have this repository support both DSTU3 and STU2 in the near future (hopefully next month).

**Comment by eikes** [comment]
Thanks for the response! I'll wait then.
